# render.yaml
services:
  - type: web
    name: clip-sneaker-service
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_PATH
        value: ./data/sneaker_database
      - key: USE_GPU
        value: false
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000